# Generated by Django 5.1.7 on 2025-09-23 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('api_key', models.TextField(blank=True, null=True)),
                ('secret_key', models.TextField(blank=True, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('angelone_password', models.TextField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users_data',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
