# Generated by Django 5.1.7 on 2025-09-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_mobile_verified',
            new_name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
