# Generated by Django 5.1.7 on 2025-10-30 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_activation', models.DateField()),
                ('activation_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'active_bot_users',
            },
        ),
    ]
