# Generated by Django 5.1.7 on 2025-10-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeOrders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='activation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='date_of_activation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
