# Generated by Django 5.0.1 on 2025-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=4)),
                ('order_type', models.CharField(choices=[('PLACE', 'Place Order'), ('EXIT', 'Exit Order'), ('MODIFY', 'Modify Order')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Order Pending'), ('PLACED', 'Order Placed'), ('EXECUTED', 'Order Executed'), ('REJECTED', 'Order Rejected'), ('CANCELLED', 'Order Cancelled'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
