# Generated by Django 5.1.7 on 2025-08-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoTrader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('symbol_name', models.CharField(max_length=20)),
                ('symbol_token', models.CharField(max_length=20)),
                ('market_capitalization', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'company_data',
            },
        ),
    ]
