# Generated by Django 5.1.7 on 2025-09-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algoTrader', '0003_all_companies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
