"""
Django settings for algoTrader project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE_PATH = os.path.join(BASE_DIR.parent.parent, ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r+%9-!(4(=#m1rg7ag-+c0ln-6_c1&#28#0s6#*dwcgotuga&w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



   


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne', # Django Channels WebSocket server
    'django.contrib.staticfiles',
    'channels',
    'users',
    'placeOrders',
    
    
    'algoTrader.apps.AlgoTraderConfig'  # Use our custom app config
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'algoTrader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'algoTrader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'algo_trader_db',  # Your database name
        'USER':'goutam_bhayal',     # Your MySQL username
        'PASSWORD':'PeAcE@123',  # Your MySQL password
        'HOST': 'db',  # Database host, 'localhost' for local development
        'PORT': '3306',      # MySQL port (default: 3306)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

# Disable UTC for Django
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS=[
    BASE_DIR,"static"
]


# Redis channel layer
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = 'redis://redis:6379/0'
#CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = False           # Important: use local timezone instead of UTC
SMARTAPI_CONFIG={
               "ANGEL_ONE_API_KEY": "0I8E0SHk",
    "ANGEL_ONE_CLIENT_CODE": "G51826344",
    "ANGEL_ONE_PASSWORD": "8852",
    "ANGEL_ONE_TOTP_SECRET": "773ESBTPTR4XCYRUDGTTQAH3KE",  # TOTP Secret for 2FA
    
}
ANGEL_ONE_API_KEY = "0I8E0SHk"
ANGEL_ONE_CLIENT_CODE = "G51826344"
ANGEL_ONE_PASSWORD = "8852"
ANGEL_ONE_TOTP_SECRET = "773ESBTPTR4XCYRUDGTTQAH3KE"
REDIS_HOST = 'redis'  # or Redis server IP if hosted remotely
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = None

# Redis Token Keys
REDIS_JWT_TOKEN_KEY = 'angel_one_jwt_token'
REDIS_FEED_TOKEN_KEY = 'angel_one_feed_token'

# Channels Configuration
ASGI_APPLICATION = 'algoTrader.asgi.application'
CELERY_TASK_ALWAYS_EAGER = False

# Login/Logout URLs
LOGIN_REDIRECT_URL = 'home'  # Changed from '/' to 'home'
LOGOUT_REDIRECT_URL = '/users/login/'
LOGIN_URL = '/users/login/'

FERNET_KEY="4aQvHm7S0ZCBew6UjzOf9_XhVxRrC68vi-bEi7mcCk8="
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'locations-yale-chains-lenders.trycloudflare.com'
]
CSRF_TRUSTED_ORIGINS = [
 'https://locations-yale-chains-lenders.trycloudflare.com']

AUTH_USER_MODEL = 'users.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'goutambhayal6266@gmail.com'
EMAIL_HOST_PASSWORD = 'caivocsipurjcjpr'
#login_to("EOKyDeOV","GTPEMQIQDRFMHAHWB7WNNGB6AI","ISRTA1374","2773")

# Default session age (2 weeks) — only used if you set session expiry to default
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14   # 14 days in seconds

# Don't expire session at browser close by default (we handle per-login)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Security: always use HTTPS in production
SESSION_COOKIE_SECURE = False      # only send cookie over HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True    # JS can't read session cookie
SESSION_COOKIE_SAMESITE = 'Lax'   # or 'Strict' depending on your needs